<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLCBsYEC\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLCBsYEC/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLCBsYEC.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLCBsYEC\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLCBsYEC\App_KernelProdContainer([
    'container.build_hash' => 'LCBsYEC',
    'container.build_id' => 'be289b2f',
    'container.build_time' => 1708941930,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLCBsYEC');
