<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8oYCMQX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8oYCMQX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8oYCMQX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8oYCMQX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8oYCMQX\App_KernelDevDebugContainer([
    'container.build_hash' => '8oYCMQX',
    'container.build_id' => '13929db7',
    'container.build_time' => 1710086020,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8oYCMQX');
