<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.8ab7f0c8.js',
                '/build/733.27b8878c.js',
                '/build/app.b2653d92.js',
            ],
            'css' => [
                '/build/733.a298894c.css',
                '/build/app.6f0f43a2.css',
            ],
        ],
    ],
],

]];
